# YAML for launching the orderer
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: orderer1-ordererorg
  labels:
    app: orderer1-ordererorg
spec:
  serviceName: orderer
  # Single instance of the Orderer Pod is needed
  replicas: 1
  selector:
    matchLabels:
      app: orderer1-ordererorg
  template:
    metadata:
      labels:
        app: orderer1-ordererorg
    spec:
      containers:
      - name: orderer1-ordererorg

        # Image used
        image: nhutori4/quyen-ordererorg-orderer1:dev

        # Uncomment the following during development/testing of the image
        imagePullPolicy: Always
        env:
          # Level of logging
          - name: FABRIC_LOGGING_SPEC
            value: INFO
          - name: CORE_PEER_TLS_ENABLED
            value: "true"
          - name: ORDERER_GENERAL_LOGLEVEL
            value: debug
          - name: ORDERER_DEBUG_BROADCASTTRACEDIR
            value: data/logs
        volumeMounts:
        # This is pointing to the PVC
        - name: orderer-ledger
          mountPath: /var/ledger


  volumeClaimTemplates:
  - metadata: 
      name: orderer-ledger
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: storageclass-orderer
      resources:
        requests:
          storage: 1Gi

---
# Expose the port 7050 as ClusterIP
apiVersion: v1
kind: Service
metadata:
  name: orderer1-ordererorg

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: orderer1-ordererorg

  ports:
    - name: orderer1-ordererorg
      port: 30740

  type: ClusterIP

---
# Expose the port 30750 as node port - NEEDED if you
# are interested in connecting to the Pods from the Host
# machine - keep in mind you would need the IP for the node
# port service
apiVersion: v1
kind: Service
metadata:
  name: orderer1-ordererorg-nodeport

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: orderer1-ordererorg

  ports:
    - name: orderer1-ordererorg-nodeport
      port: 30740
      nodePort: 30740

  type: NodePort
