# YAML for launching the orderer
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: peer1-thuduchospital
  labels:
    app: peer1-thuduchospital
spec:
  serviceName: peer1-thuduchospital
  replicas: 1
  selector:
    matchLabels:
      app: peer1-thuduchospital
  template:
    metadata:
      labels:
        app: peer1-thuduchospital
    spec:
      containers:
      - name: peer1-thuduchospital
        # Image used
        image: nhutori4/quyen-peer1-thuduc:dev
        # Uncomment the following during development/testing of the image
        imagePullPolicy: Always
        env:
          - name: FABRIC_LOGGING_SPEC
            value: INFO
        volumeMounts:
        - name: peer1-thuduchospital-ledger
          mountPath: /var/ledger
        - name: dockersock
          mountPath: /var/run/docker.sock
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
  volumeClaimTemplates:
  - metadata: 
      name: peer1-thuduchospital-ledger
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: storageclass-thuduchospital
      resources:
        requests:
          storage: 1Gi

---
# Expose the port 7051 as ClusterIP
apiVersion: v1
kind: Service
metadata:
  name: peer1-thuduchospital

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: peer1-thuduchospital

  ports:
    - name: peer1-thuduchospital
      port: 30741
    - name: peer1-thuduchospital-cc-clusterip
      port: 30742

  type: ClusterIP

---
# Expose the port 30751 as node port -  NEEDED if you
# are interested in connecting to the Pods from the Host
# machine - keep in mind you would need the IP for the node
# port service
apiVersion: v1
kind: Service
metadata:
  name: peer1-thuduchospital-nodeport

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: peer1-thuduchospital

  ports:
    - name: peer1-thuduchospital-nodeport-751
      port: 30741
      nodePort: 30741
    - name: peer1-thuduchospital-cc-nodeport-752
      port: 30742
      nodePort: 30742

  type: NodePort
